databases:
  - name: 
    plan: free
    databaseName: confeitaria
    user: BAG

services:
  - type: web
    plan: free
    name: confeitaria
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn confeitaria.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: confeitaria
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4