# Generated by Django 5.1 on 2024-09-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_delete_tortas_remove_bolos_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destaques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
